# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Proud Generalist
tagline:          #
description:      A millennial's lessons building a career as a generalist
url:              proudgeneralist.github.io
baseurl:          /

author:
  name:           'Hanna-Mari'
  url:            https://twitter.com/hmkirs

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/proudgeneralist
  
